controller:
  replicaCount: 2
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      external-dns.alpha.kubernetes.io/hostname: nginx-internal.prod-sa1.osmose.paytmlabs.com
